=== hermesdt/AFA2/Plugins/Plugin.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT plugin (metadata,techniques)>

<!ELEMENT metadata (name, os, category, last_updated, author?, tags?, description?)>

<!ELEMENT name (#PCDATA)><!-- Nombre del plugin -->
<!ELEMENT os (#PCDATA)><!-- Sistema operativo -->
<!ELEMENT category (#PCDATA)><!-- Sistema operativo -->
<!ELEMENT author (#PCDATA)><!-- Nombre del author -->
<!ELEMENT last_updated (#PCDATA)><!-- Fecha ultima actualizacion -->
<!ELEMENT tags (tag)*><!-- Conjunto de tags asociados -->
<!ELEMENT tag (#PCDATA)><!-- Etiqueta que aporta informacion extra -->
<!ELEMENT description (#PCDATA)><!-- Descripcion -->

<!ELEMENT techniques (find_file)+>

<!ELEMENT find_file (name?, location, content?, hash?,  recursively?, mimetype?, installed?, on_success?)>

<!ELEMENT location (#PCDATA)><!--  -->
<!ELEMENT content (#PCDATA)>
<!ELEMENT hash (type, value)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT mimetype (#PCDATA)>
<!ELEMENT recursively (#PCDATA)>
<!ELEMENT installed (#PCDATA)>
<!ELEMENT on_success (#PCDATA)>

=== hermesdt/AFA2/Plugins/MacOs/GnuPG.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "../Plugin.dtd">
<plugin>
  <metadata>
    <name>GnuPG</name>
    <os>MacOs</os>
    <category>MacOs</category>
    <author>Alvaro</author>
    <description></description>
    <last_updated>1301085134000</last_updated>
    <tags>
      <tag>tag_4</tag>
      <tag>tag_5</tag>
      <tag>tag_6</tag>
    </tags>
  </metadata>
  <techniques>
    <technique>
      <name>GnuPG</name>
      <type>find_file</type>
      <location>/Principal/Library/Documentation</location>
      <recursively>false</recursively>
    </technique>
    <technique>
      <name>gpg.docs.english.pkg</name>
      <type>find_file</type>
      <location>/Principal/Library/Receipts</location>
      <recursively>false</recursively>
    </technique>
  </techniques>
</plugin>

=== hermesdt/AFA2/Plugins/MacOs/Cryptix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "../Plugin.dtd">
<plugin>
  <metadata>
    <name>Cryptix</name>
    <os>MacOs</os>
    <category>MacOs</category>
    <last_updated>1364412039000</last_updated>
    <author>Alvaro</author>
    <tags>
      <tag>tag_2</tag>
      <tag>tag_3</tag>
      <tag>tag_4</tag>
      <tag>tag_6</tag>
    </tags>
    <description>Busca trazas de la aplicacion cryptix</description>
  </metadata>
  <techniques>
    <find_file>
      <name>Cryptix.app</name>
      <location>/Principal/Applications</location>
      <recursively>false</recursively>
    </find_file>
    <find_file>
      <location>/Principal/Users</location>
      <content>Cryptix</content>
      <recursively>true</recursively>
    </find_file>
  </techniques>
</plugin>

=== hermesdt/AFA2/Plugins/Linux/GnuPG.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plugin SYSTEM "../Plugin.dtd">
<plugin>
  <metadata>
    <name>GnuPG</name>
    <os>Linux</os>
    <category>Linux</category>
    <last_updated>1364412039000</last_updated>
    <author>Alvaro</author>
    <tags>
      <tag>tag_1</tag>
      <tag>tag_2</tag>
      <tag>tag_3</tag>
      <tag>tag_7</tag>
    </tags>
    <description></description>
  </metadata>
  <techniques>
    <find_file>
      <name>gpg</name>
      <location>/usr/bin</location>
      <recursively>false</recursively>
    </find_file>
    <find_file>
      <name>gpg.1.gz</name>
      <location>/usr/share/man</location>
      <recursively>true</recursively>
    </find_file>
    <find_file>
      <location>/usr/share/man</location>
      <hash>
        <type>MD5</type>
        <value>dd49cfeb3b7f53f0521936153bd35eca</value>
      </hash>
      <recursively>true</recursively>
    </find_file>
    <find_file>
      <location>/usr/share/vin/vim73</location>
      <content>syn keyword gpgCommand  contained skipwhite nextgroup=gpgArg</content>
      <recursively>true</recursively>
    </find_file>
    <find_file>
      <location>/</location>
      <content>1024x600</content>
      <recursively>false</recursively>
      <mimetype>image/gif</mimetype>
    </find_file>
  </techniques>
</plugin>
